### ISSUE TITLE
Project setup  

### ISSUE THREAD

**Issue by mitjarogl** [mattstauffer/suggestive#14]
@mattstauffer can you please provide setup for project to work. It would be nice to add changelog to see past work.

**Comment by mattstauffer** [comment]
@mitjarogl It's a bit too hectic-work-on-my-free-time to merit a change log right now. It's not even really in alpha, right now, it's just me hacking around. Checkout the commit history for the best changelog I can give right now. :)

But I'll definitely get setup instructions!

**Comment by mattstauffer** [comment]
@mitjarogl 
https://github.com/mattstauffer/suggestive/blob/master/readme.md

Let me know how that works out for you. Thanks!
