### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dehboris** [mattstauffer/suggestive#15]
I would like to understand why you used `windows.Vue`.
And what is the difference between `windows.Vue = require('vue')` and  `import view from ' View'`

**Comment by mattstauffer** [comment]
`window.Vue` is the same as `Vue` without setting the scope explicitly. Not
sure what motivated me to put the window. on it.. maybe just trying to be
more explicit.

`require(‘vue’)` and `import due from Vue` are the same, but the first is
Browserify and the second is ES2015. Just two different loading standards.

**Comment by mattstauffer** [comment]
`window.Vue` is the same as `Vue` without setting the scope explicitly. Not sure what motivated me to put the window. on it.. maybe just trying to be more explicit.

`require('vue')` and `import due from Vue` are the same, but the first is Browserify and the second is ES2015. Just two different loading standards.
