### ISSUE TITLE
Add additional documentation for how to set up OAuth Integrations for GitHub and Twitter

### ISSUE THREAD

**Issue by kkoppenhaver** [mattstauffer/suggestive#16]
Maybe link to tutorials on how these things work, how to get the correct credentials, etc...

**Comment by JacobBennett** [comment]
Was just thinking about this the other day. Where would be the best spot for this? In the Wiki? Or in the  Readme? Thoughts @mattstauffer.

Would be happy to help with this as I know it is confusing.

**Comment by mattstauffer** [comment]
Readme, I think. I hate using the wiki, folks almost never use them so the writing goes unused.

**Comment by JacobBennett** [comment]
Good to close on this @mattstauffer ?

**Comment by mattstauffer** [comment]
:+1: Thanks @JacobBennett!
