### ISSUE TITLE
Prop syncing, rly Matt...? 😏

### ISSUE THREAD

**Issue by blomdahldaniel** [mattstauffer/suggestive#18]
First and foremost thank you Matt for all that you do for this community. The podcast, twitch (I love that you don't know the slang and tech there 😝) your blog and for your talk about empathy at the last laracon it was great! Also, I just wanna say that I, from my Swedish eyes, appreciate what seem to be your political view at your twitter. You Americans scare the crap out of us here in Sweden, donno what to think about your country no more I must say... But then it gives me a bit more comfort when I see your tweets! :p 
And I also just want to say that this repo has helped me SO MUCH in understanding how to set up a laravel backend with vue-router frontend. So big thank you for that! This is something that I have had a hard time finding any real good example/resource of. Haven't seen anything that fits that gap enough imo but this project is a great example. So big thanks again!

So, enough with the fanboii talk, lets get serious..

I was going through your code and I happened to see some prop syncing... Dude... 😏
I think I heard you on the Laracast podcast and you said you where gonna sort that out right..? ;) So I just wanted to poke you a bit and I would love to see this project with Vue 2.0 just to be able to sneak peek at the structure and all in an self educational purpose. 

You're awesome!

**Comment by mattstauffer** [comment]
Yah, dude, I wrote this thing back when prop syncing wasn't faux pas.

I'm much more interested in launching it than I am upgrading it to Vue 2.0, but I'd be perfectly happy for folks to submit PRs to make it not use sync if they'd like. :)

Glad to hear it's helped! Thanks for your kind words!
