### ISSUE TITLE
Update to use Axios instead of vue-resource

### ISSUE THREAD

**Issue by JacobBennett** [mattstauffer/suggestive#26]
After the announcement that `vue-resource` is [being retired](https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4#.z79tiw7f3), would be good to get a jump on switching to [Axios](https://github.com/mzabriskie/axios). 

This still requires the [IE polyfills](https://github.com/stefanpenner/es6-promise) which are currently implemented in PR #24.

Switching to Axios would also allow us to remove the double `Promise` wrapping in the `topics.js` object also included in PR #24.

**Comment by mattstauffer** [comment]
Closed in #28
