### ISSUE TITLE
[Idea] - Integrate iTunes Search API?

### ISSUE THREAD

**Issue by vmitchell85** [mattstauffer/suggestive#36]
What if you could search for any podcast to recommend a topic for. This would then make it simple to suggest topics for a podcast that isn't on the site yet. This also would allow scraping some data regarding the podcast.

I think we would be able to get old episode data to display as well.

The biggest issue with this is matching up admins with podcasts... as there would need to be some validation of sorts... not sure about that. And some mechanism to mark topics as "covered" if the podcast owner hasn't matched up with their podcast yet.

Just some ideas... didn't want to start hacking on them if there isn't any interest...

Thanks,
- Vince

**Comment by mattstauffer** [comment]
Right now, at least, this isn't a SaaS that's hosting multiple entities; it's a one-off thing. Each person who wants to use it has to install it separately for themselves. So this would preclude this sort of functionality unless that foundational architecture were changed. Great idea, though!
